=== CodewithRajDeep/Basic-to-advance-in-XML/studentdetails.dtd
<!DOCTYPE studentDetails SYSTEM "studentDetails.dtd">

<!-- studentDetails.dtd -->

<!ELEMENT studentDetails (student+)>
<!ELEMENT student (firstName, middleName?, lastName, SAP_ID, email, address, phone, yearOfJoining, locality, city, state, country, pinCode)>
<!ATTLIST student mandatory (yes) #REQUIRED>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT middleName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT SAP_ID (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT yearOfJoining (#PCDATA)>
<!ELEMENT locality (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT pinCode (#PCDATA)>

=== CodewithRajDeep/Basic-to-advance-in-XML/studentdetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentDetails SYSTEM "studentdetails.dtd">

<studentDetails>

<student mandatory="yes">
<firstName>John</firstName>
<middleName>David</middleName>
<lastName>Doe</lastName>
<SAP_ID>1234567890</SAP_ID>
<email>john.doe@example.com</email>
<address>123 Main Street</address>
<phone>123-456-7890</phone>
<yearOfJoining>2023</yearOfJoining>
<locality>North Campus</locality>
<city>New Delhi</city>
<state>Delhi</state>
<country>India</country>
<pinCode>110001</pinCode>
</student>

</studentDetails>
